library(shiny)
library(bslib)

data_path <- "data/GDS5826.csv"

df <- read.csv(data_path)

column_names <- colnames(df)

gene_labels <- column_names[1:2]

sample_names <- column_names[3:length(column_names)]

ui <- fluidPage(
  theme = bslib::bs_theme(version = 4, bootswatch = "flatly"),
  titlePanel("Gene Expression Data for Multiple Myeloma Cell Lines With Acquired Resistance to Chemotherapeutic Agent Carfilzomib"),
  sidebarLayout(
    sidebarPanel(
      # choose which samples to display
      checkboxGroupInput(
        "samples", 
        "Samples", 
        sample_names, 
        selected = sample_names
      )       
    ),
    mainPanel(
      tabsetPanel(
        tabPanel("Data and Project Description", textOutput("data_and_project_description")),
        tabPanel("Raw Data", tableOutput("raw_data")),
        tabPanel("Gene Expression Histogram", textOutput("no_selection")),
        tabPanel("Heirarchical Cluster Analysis", textOutput("no_selection")),
        tabPanel("Differential Gene Expression Analysis", textOutput("no_selection")),
        tabPanel("Pathway Enrichment Analysis", textOutput("no_selection"))
      )
    )
  )
)

server <- function(input, output) {

    output$raw_data <- renderTable({
      return(head(df[, c(gene_labels, input$samples)], 10))
    })

    output$data_and_project_description <- renderText({
      return(
        "GENERATED BY COPILOT. REPLACE LATER. This dataset contains gene 
        expression data for multiple myeloma cell lines with acquired 
        resistance to the chemotherapeutic agent carfilzomib. The data was 
        generated using the Affymetrix Human Genome U133 Plus 2.0 Array 
        platform. The dataset contains gene expression data for 22,283 genes 
        in 8 cell lines. The dataset also contains information on the IC50 
        values of the cell lines to carfilzomib."
      )
    })

    output$no_selection <- renderText({
      return("Select a visualization type")
    })
}
 
shinyApp(ui, server)
